== Synopsis

[.cli-opt]#*slurm-web-show-conf*# `[_GENERAL OPTIONS_] {gateway,agent}`

== Description

Slurm-web is a web dashboard for Slurm HPC cluster. Its architecture is based on
two components: the gateway and agents. This command is a utility to dump
current values of the configuration settings of these components with their
origin, by protecting sensible data such as passwords.

== General Options

The name of the component ([.cli-optval]#gateway# or [.cli-optval]#agent#) for
which the configuration is dumped must be given in argument.

Other general options are available:

[.cli-opt]#*-h, --help*#::
  Show this help message and exit.

[.cli-opt]#*-v, --version*#::
  Show Slurm-web version number and exit.

[.cli-opt]#*--debug*#::
  Enable debug mode with more debug messages in logs.

[.cli-opt]#*--log-flags*=#[.cli-optval]##_FLAGS_##::
  Libraries for which logs (except debug messages) are enabled. Multiple values
  can be selected among _slurmweb_, _rfl_, _racksdb_, _werkzeug_, _urllib3_.
  Special value *ALL* enable logs for all libraries. Default value is *ALL*.
  This option can be used to filter out logs of too verbose libraries.

[.cli-opt]#*--log-component*=#[.cli-optval]##_COMPONENT_##::
  Add _COMPONENT_ as prefix of all log entries.

[.cli-opt]#*--debug-flags*=#[.cli-optval]##_FLAGS_##::
  Libraries for which debug logs are enabled when [.cli-opt]#`--debug`#
  option is used. Multiple values can be selected among _slurmweb_, _rfl_,
  _racksdb_, _werkzeug_, _urllib3_. Special value *ALL* enable debug logs for
  all libraries. Default value is *slurmweb*.

[.cli-opt]#*--conf-defs*=#[.cli-optval]##_DEFS_##::
  Path to Slurm-web component YAML configuration definition file. Default value
  is [.path]#`/usr/share/slurm-web/conf/gateway.yml`# for the gateway and
  [.path]#`/usr/share/slurm-web/conf/agent.yml`# for the agent.

[.cli-opt]#*--conf*=#[.cli-optval]##_CONF_##::
  Path to Slurm-web component site configuration file. Default value is
  [.path]#`/etc/slurm-web/gateway.ini`# for the gateway and
  [.path]#`/etc/slurm-web/agent.ini`# for the agent.

== Exit status

*0*::
  `slurm-web-show-conf` has processed command with success.

*1*::
  `slurm-web-show-conf` encountered an error.
