#!/usr/bin/env python3
#
# Copyright (c) 2023-2024 Rackslab
#
# This file is part of Slurm-web.
#
# SPDX-License-Identifier: MIT

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "lib"))

from devenv.main import main

if __name__ == "__main__":
    main()
