---
# Define DPI/sizes for which PNG bitmaps versions of SVG diagrams must be
# generated.
diagrams:
  modules/overview/images/slurm-web_transparent_cache.svg: medium
  modules/overview/images/slurm-web_metrics.svg: large
  modules/overview/images/arch/slurm-web_architecture.svg: medium
  modules/overview/images/arch/slurm-web_distribution.svg: medium
  modules/overview/images/arch/slurm-web_integration.svg: medium
  modules/overview/images/arch/slurm-web_protocols.svg: medium
  modules/overview/images/arch/slurm-web_deployment_mono-cluster_collocated.svg: medium
  modules/overview/images/arch/slurm-web_deployment_mono-cluster_separated.svg: medium
  modules/overview/images/arch/slurm-web_deployment_multi-clusters.svg: medium
  modules/conf/images/slurmrestd/slurmrestd_access_modes.svg: large
  modules/conf/images/slurmrestd/slurmrestd_access_modes_unix_jwt_auto.svg: large
  modules/conf/images/slurmrestd/slurmrestd_access_modes_unix_jwt_static.svg: large
  modules/conf/images/slurmrestd/slurmrestd_access_modes_unix_local.svg: large
  modules/conf/images/slurmrestd/slurmrestd_access_modes_inet_jwt_auto.svg: large
  modules/conf/images/slurmrestd/slurmrestd_access_modes_inet_jwt_static.svg: large
