export const REST_URI = 'http://server.local:8000/slurm-restapi'
export const LOGIN_URL = REST_URI + '/login'
export const LOGOUT_URL = REST_URI + '/logout'

export const FETCH_JOBS = 'FETCH_JOBS'
export const FETCH_CLUSTER = 'FETCH_CLUSTER'
export const FETCH_RACKS = 'FETCH_RACKS'
export const FETCH_NODES = 'FETCH_NODES'
export const FETCH_PARTITIONS = 'FETCH_PARTITIONS'
export const FETCH_QOS = 'FETCH_QOS'
export const FETCH_RESERVATIONS = 'FETCH_RESERVATIONS'
